[project]
name = "advent-of-code"
version = "2025.0.1"
description = "Advent Of Code 2024, 2025"
readme = "README.md"
requires-python = ">=3.13.2"
dependencies = [
    "galois>=0.4.9",
    "networkx>=3.6.1",
    "numpy>=2.3.5",
    "scipy>=1.16.3",
    "sympy>=1.14.0",
]
