[project]
name = "advent-of-code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.2"
dependencies = [
    "networkx>=3.6.1",
    "numpy>=2.3.5",
    "scipy>=1.16.3",
    "sympy>=1.14.0",
]
